spring.application.name=DestinyDeveloperProject
spring.datasource.url=jdbc:mysql://localhost:3306/DestinyDev?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=user
spring.security.user.password=Nagar
spring.mvc.view.prefix=./views/
spring.mvc.view.suffix=.jsp
paypal.mode=sandbox
paypal.client.id="Your_Client_ID"
paypal.client.secret="Your_Client_Secret"

